//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher
    {
        public int Publisher_ID { get; set; }
        public string Publisher_Name { get; set; }
        public string Country { get; set; }
        public string City { get; set; }

        public ICollection<Book> Books { get; set; }
    }
}
